# Generated by Django 3.2.9 on 2021-11-24 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, db_index=True, default=None, max_length=150, null=True, verbose_name='Section Name')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Name')),
                ('raw_value', models.TextField(blank=True, null=True, verbose_name='Raw Value')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': 'site preference',
                'verbose_name_plural': 'site preferences',
                'abstract': False,
                'unique_together': {('instance', 'section', 'name')},
            },
        ),
    ]
