language: python
python:
  - 3.4
  - 3.5
  - 3.6
env:
  - DJANGO='django>=2.0,<2.1'
  - DJANGO='https://github.com/django/django/archive/master.tar.gz'
install:
  - pip install pipenv
  - pipenv install --system --deploy
  - pip install -e .
script:
  - DJANGO_SETTINGS_MODULE=cbvadmin.tests.test_settings py.test cbvadmin/tests --cov=cbvadmin
notifications:
  email: false
matrix:
  allow_failures:
    - env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
after_success:
  - bash <(curl -s https://codecov.io/bash)
